version: "3.9"

volumes:
  postgres:
    driver: local
  initpostgres:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './init'



services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: 'postgres'
      PGDATA: '/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    volumes:
      - initpostgres:/docker-entrypoint-initdb.d
      - postgres:/var/lib/postgresql/data
