server:
  port: 8080
  servlet:
    context-path: '/api'

springdoc:
  swagger-ui:
    path: '/swagger-ui.html'
  api-docs:
    path: '/api-docs'

spring:
  liquibase:
    enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/tenses_db'
    username: 'tenses_app'
    password: 'tenses_app'

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  sql:
    init:
      mode: embedded
      schema-locations: classpath*:database/initDB.sql
      data-locations: classpath*:database/populateDB.sql

logging:
  level:
    com:
      baeldung: TRACE

