server:
  port: 8080
  servlet:
    context-path: '/api'

springdoc:
  swagger-ui:
    path: '/swagger-ui.html'
  api-docs:
    path: '/api-docs'

spring:
  liquibase:
    enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/tense_db'
    username: 'postgres'
    password: 'postgres'
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect

logging:
  level:
    com:
      baeldung: TRACE

