server:
  port: 8080
  servlet:
    context-path: '/api'

springdoc:
  swagger-ui:
    path: '/swagger-ui.html'
  api-docs:
    path: '/api-docs'

spring:
#  liquibase settings
  liquibase:
    enabled: true
    change-log: classpath*:database/changelog/db.changelog.yaml
    liquibase-schema: tenses
    default-schema: tenses
#    datasource settings
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/tenses_db'
    username: 'tenses_app'
    password: 'tenses_app'
#    jpa settings
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never

logging:
  level:
    com:
      baeldung: TRACE

